// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageType.proto

#include "MessageType.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace com {
namespace genesis {
namespace protobuf {
}  // namespace protobuf
}  // namespace genesis
}  // namespace com
void InitDefaults_MessageType_2eproto() {
}

constexpr ::google::protobuf::Metadata* file_level_metadata_MessageType_2eproto = nullptr;
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors_MessageType_2eproto[4];
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_MessageType_2eproto = nullptr;
const ::google::protobuf::uint32 TableStruct_MessageType_2eproto::offsets[1] = {};
static constexpr ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static constexpr ::google::protobuf::Message* const* file_default_instances = NULL;

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_MessageType_2eproto = {
  {}, AddDescriptors_MessageType_2eproto, "MessageType.proto", schemas,
  file_default_instances, TableStruct_MessageType_2eproto::offsets,
  file_level_metadata_MessageType_2eproto, 0, file_level_enum_descriptors_MessageType_2eproto, file_level_service_descriptors_MessageType_2eproto,
};

::google::protobuf::internal::DescriptorTable descriptor_table_MessageType_2eproto = {
  false, InitDefaults_MessageType_2eproto, 
  "\n\021MessageType.proto\022\024com.genesis.protobu"
  "f\032 google/protobuf/descriptor.proto*\032\n\rM"
  "essageTarget\022\t\n\005ERROR\020\001*\310\001\n\rCSMessageTyp"
  "e\022\020\n\014CS_HANDSHAKE\020\001\022\020\n\014CS_TIME_SYNC\020\002\022\022\n"
  "\016CS_CLIENT_TYPE\020\003\022\020\n\014CS_ROBOT_POS\020\025\022\024\n\020C"
  "S_ROBOT_BATTERY\020\026\022\023\n\017CS_ROBOT_SWITCH\020\027\022\022"
  "\n\016CS_ROBOT_ERROR\020\030\022\023\n\017CS_ROBOT_STATUS\020\031\022"
  "\031\n\025CS_REQUEST_ROBOT_INFO\020\037*\207\001\n\rSCMessage"
  "Type\022\026\n\022SC_HANDSHAKE_REPLY\020\001\022\032\n\026SC_MSG_C"
  "AN_NOT_PROCESS\020\002\022\030\n\024SC_CLIENT_DATA_ERROR"
  "\020\003\022\026\n\022SC_TIME_SYNC_REPLY\020\004\022\020\n\014SC_ROBOT_P"
  "OS\020\037*c\n\rSSMessageType\022\020\n\014SS_HANDSHAKE\020\001\022"
  "\026\n\022SS_HANDSHAKE_REPLY\020\002\022\020\n\014SS_HEARTBEAT\020"
  "\003\022\026\n\022SS_HEARTBEAT_REPLY\020\004:_\n\017cs_message_"
  "type\022\037.google.protobuf.MessageOptions\030\321\206"
  "\003 \001(\0162#.com.genesis.protobuf.CSMessageTy"
  "pe:_\n\017sc_message_type\022\037.google.protobuf."
  "MessageOptions\030\322\206\003 \001(\0162#.com.genesis.pro"
  "tobuf.SCMessageType:_\n\017ss_message_type\022\037"
  ".google.protobuf.MessageOptions\030\323\206\003 \001(\0162"
  "#.com.genesis.protobuf.SSMessageType:_\n\006"
  "TARGET\022!.google.protobuf.EnumValueOption"
  "s\030\321\206\003 \001(\0162#.com.genesis.protobuf.Message"
  "Target:\005ERRORB\rB\013MessageType"
,
  "MessageType.proto", &assign_descriptors_table_MessageType_2eproto, 948,
};

void AddDescriptors_MessageType_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_google_2fprotobuf_2fdescriptor_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_MessageType_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_MessageType_2eproto = []() { AddDescriptors_MessageType_2eproto(); return true; }();
namespace com {
namespace genesis {
namespace protobuf {
const ::google::protobuf::EnumDescriptor* MessageTarget_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[0];
}
bool MessageTarget_IsValid(int value) {
  switch (value) {
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* CSMessageType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[1];
}
bool CSMessageType_IsValid(int value) {
  switch (value) {
    case 1:
    case 2:
    case 3:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 31:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* SCMessageType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[2];
}
bool SCMessageType_IsValid(int value) {
  switch (value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 31:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* SSMessageType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[3];
}
bool SSMessageType_IsValid(int value) {
  switch (value) {
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::com::genesis::protobuf::CSMessageType, ::com::genesis::protobuf::CSMessageType_IsValid>, 14, false >
  cs_message_type(kCsMessageTypeFieldNumber, static_cast< ::com::genesis::protobuf::CSMessageType >(1));
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::com::genesis::protobuf::SCMessageType, ::com::genesis::protobuf::SCMessageType_IsValid>, 14, false >
  sc_message_type(kScMessageTypeFieldNumber, static_cast< ::com::genesis::protobuf::SCMessageType >(1));
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::com::genesis::protobuf::SSMessageType, ::com::genesis::protobuf::SSMessageType_IsValid>, 14, false >
  ss_message_type(kSsMessageTypeFieldNumber, static_cast< ::com::genesis::protobuf::SSMessageType >(1));
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::com::genesis::protobuf::MessageTarget, ::com::genesis::protobuf::MessageTarget_IsValid>, 14, false >
  TARGET(kTARGETFieldNumber, static_cast< ::com::genesis::protobuf::MessageTarget >(1));

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
}  // namespace genesis
}  // namespace com
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
